WebApplication1/WebApplication1/Controllers/RezervationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class RezervationController : Controller
    {
        // GET: Rezervation
        public ActionResult Index()
        {
            if (Session["session_giris"] != null)
            {
               return View();
            }
            else
            {
                return RedirectToAction("Giris", "Customer");
            }
            
        }
    }
}

WebApplication1/WebApplication1/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class VehicleController : Controller
    {
        Db_AracKiralamaEntities db = new Db_AracKiralamaEntities();
       //GET: Vehicle
        public ActionResult Index()
        {
            return View(db.Tb1_Araclar.ToList());
        }
        public ActionResult Details(int? id)
        {
            Tb1_Araclar arac_bilgileri = db.Tb1_Araclar.Find(id);
            return View(arac_bilgileri);
        }

        [HttpGet]
        public ActionResult Rezervation(int? id)
        {
            Tb1_Araclar arac_bilgileri = db.Tb1_Araclar.Find(id);
            ViewData["Marka"] = arac_bilgileri.Marka;
            ViewData["Model"] = arac_bilgileri.Model;
            ViewData["Fiyat"] = arac_bilgileri.Fiyat;
            return View();
        }
        [HttpPost]
        public ActionResult Rezervation([Bind(Include = "RezervationId,AracId,TcKimlik,AdSoyad,AlmaTarihi,TeslimTarihi,Ucret")]Tb1_Rezervasyonlar rezervasyon)     
        {
            if(ModelState.IsValid)
            {
                db.Tb1_Rezervasyonlar.Add(rezervasyon);
                db.SaveChanges();
            }
            ViewBag.Message = "Tebrikler Rezervasyon İşleminiz Tamamlanmıştır.";
            return View();
        }
    }
}   

WebApplication1/WebApplication1/Views/Vehicle/Details.cshtml
@model WebApplication1.Models.Tb1_Araclar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <link href="~/Css/stilim.css" rel="stylesheet" />
</head>
<body>
    <div>
        <h1>Sakarya Bip Otomotiv</h1>
        <h3>Araç Bilgileri</h3>
        <hr />
        <dl class="dl-horizontal">

            @{
                var dir = "~/VehicleImages/" + Html.DisplayFor(model => model.AracId) + ".jpg";
                string FolderPath = Path.Combine(Server.MapPath(dir));
                if (System.IO.File.Exists(FolderPath))
                {
                    <img src="@Url.Content(dir)" width="300" />
                }
            }
            <dt>
                @Html.DisplayNameFor(model => model.Marka)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Marka)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Model)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Model)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModelYili)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModelYili)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Yakit)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Yakit)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Vites)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Vites)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fiyat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fiyat)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Rezervasyon", "Rezervation", new { id = Model.AracId }) |
        @Html.ActionLink("Araç listesi", "Index")
    </p>
</body>
</html>

WebApplication1/WebApplication1/Views/Vehicle/Index.cshtml
@model IEnumerable<WebApplication1.Models.Tb1_Araclar>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Css/stilim.css" rel="stylesheet" />
</head>
<body>
   <h1> Sakarya  Bip Otomotiv</h1>
    <h3>Arac Kiralama</h3>
    <table class="table" border="1" cellpadding="5" cellspacing="0">
        <tr>
            <th>Resim</th>
            <th>
               Marka
            </th>
            <th>
               Model
            </th>
            <th>
                ModelYili
            </th>
            <th>
                Yakit
            </th>
            <th>
               Vites
            </th>
            <th>
              Fiyat
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @{ 
                    var dir = "~/VehicleImages/" + item.AracId + ".jpg";
                    string FolderPath = Path.Combine(Server.MapPath(dir));
                    if (System.IO.File.Exists(FolderPath))
                    { 
                    <img src="@Url.Content(dir)" with="100"/>
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelYili)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yakit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vites)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fiyat)
            </td>
            <td>

                @Html.ActionLink("Detay", "Details", new { id = item.AracId }) |
                @Html.ActionLink("Rezervasyon", "Rezervation", new { id = item.AracId }) |
            </td>
        </tr>
    }
    
    </table>
    <p>
        @Html.ActionLink("Ana Sayfa", "Index", "Home") |
        @Html.ActionLink("Hakkımızda", "About", "Home") |
        @Html.ActionLink("Araçlar", "Index", "Vehicle") |
        @Html.ActionLink("Rezervasyonlarım", "Index", "Rezervation")|
    </p>
</body>
</html>

WebApplication1/WebApplication1/Views/Vehicle/Rezervation.cshtml
@model WebApplication1.Models.Tb1_Rezervasyonlar


@{
    Layout = null;
}
<script type="text/javascript">
    function ToplamUcretHesapla()
    {
        var dt1 = new Date(AlmaTarihi.Value);
        var dt2 = new Date(TeslimTarihi.Value);
        var timeDiff = Math.abs(dt2.getTime() - dt1.getTime());
        var daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24));
        var birimFiyat = parseFloat(Fiyat.Value);
        Ucret.Value = parseInt(daysDiff) * birimFiyat;
    }
    </script>






<!DOCTYPE html>
                
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Rezervation</title>                                          
    <link href="~/Css/stilim.css" rel="stylesheet" />
</head>
<body>
    <div>
        <h1>Sakarya Bip Otomotiv</h1>
        <h3>ARAÇ Bilgileri </h3>
        <table border="1" cellpadding="5" cellspacing="0" width="600">
            <tr>
                <td width="40%">
                    <h4> Araç No: @Url.RequestContext.RouteData.Values["id"] </h4>
                    <h4> Araç Markası: @ViewData["Marka"]</h4>
                    <h4> Araç Moddeli: @ViewData["Model"]</h4>
                </td>
                <td>
                    @{
                        var dir = "~/VehicleImages/" + Url.RequestContext.RouteData.Values["id"] + ".jpg";
                        <img src="@Url.Content(dir)" width="300" />

                    }
                </td>
            </tr>
        </table>
        @{
            if (ViewBag.Message == null)
            {
                <h3>Rezervasyon formu</h3>
                using (Html.BeginForm())



                {
        <table border="1" cellpadding="5" cellspacing="0" width="600">
            <tr>
                @Html.Hidden("AracId", Url.RequestContext.RouteData.Values["id"])
                <td width="40%">Tc Kimlik  </td>
                <td width="30%">@Html.EditorFor(Model => Model.TcKimlik)  </td>

            </tr>
            <tr>
                <td width="30%">Ad Soyad  </td>
                <td width="30%">@Html.EditorFor(Model => Model.AdSoyad)  </td>

            </tr>
            <tr>
                <td width="30%"> Alma Tarihi  </td>
                <td width="30%">@Html.EditorFor(Model => Model.AlmaTarihi)  </td>

            </tr>
            <tr>
                <td width="30%">Teslim Tarihi  </td>
                <td width="30%">@Html.TextBoxFor(Model => Model.TeslimTarihi, new { onbulr = "ToplamUcretHesapla()" })  </td>

            </tr>
            <tr>
                <td width="30%">Fiyat (Günlük)  </td>
                <td width="30%">@Html.TextBox("Fiyat", ViewData["Fiyat"]) TL </td>

            </tr>
            <tr>
                <td width="30%"> Ücret (Toplam)  </td>
                <td width="30%">@Html.EditorFor(Model => Model.Ucret) TL </td>

            </tr>
            <tr>
                <td width="30%">Ad Soyad  </td>
                <td><input type="submit" value="Rezervasyon Yap" /> </td>

            </tr>
         </table>
                }
            }
        }

    </div>
    <h4>@ViewBag.Message </h4>
    <p>

        @Html.ActionLink("Araç Detayı", "Details", new { id = Url.RequestContext.RouteData.Values["id"] })
        @Html.ActionLink("Araç Listesi" , "Index")
    </p>
</body>
</html>