WebApplication1/WebApplication1/Controllers/VehicleYonetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.IO;

namespace WebApplication1.Controllers
{
    public class VehicleYonetController : Controller
    {
        private Db_AracKiralamaEntities db = new Db_AracKiralamaEntities();

        // GET: VehicleYonet
        public ActionResult Index()
        {
            return View(db.Tb1_Araclar.ToList());
        }

        // GET: VehicleYonet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb1_Araclar tb1_Araclar = db.Tb1_Araclar.Find(id);
            if (tb1_Araclar == null)
            {
                return HttpNotFound();
            }
            return View(tb1_Araclar);
        }

        // GET: VehicleYonet/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VehicleYonet/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AracId,Marka,Model,ModelYili,Yakit,Vites,Fiyat")] Tb1_Araclar tb1_Araclar)
        {
            if (ModelState.IsValid)
            {
                db.Tb1_Araclar.Add(tb1_Araclar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb1_Araclar);
        }

        // GET: VehicleYonet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb1_Araclar tb1_Araclar = db.Tb1_Araclar.Find(id);
            if (tb1_Araclar == null)
            {
                return HttpNotFound();
            }
            return View(tb1_Araclar);
        }

        // POST: VehicleYonet/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AracId,Marka,Model,ModelYili,Yakit,Vites,Fiyat")] Tb1_Araclar tb1_Araclar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb1_Araclar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb1_Araclar);
        }

        // GET: VehicleYonet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tb1_Araclar tb1_Araclar = db.Tb1_Araclar.Find(id);
            if (tb1_Araclar == null)
            {
                return HttpNotFound();
            }
            return View(tb1_Araclar);
        }

        // POST: VehicleYonet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tb1_Araclar tb1_Araclar = db.Tb1_Araclar.Find(id);
            db.Tb1_Araclar.Remove(tb1_Araclar);
            db.SaveChanges();
            //Araç Resmi Siliniyor
            String ImageFileName = id.ToString() + ".jpg";
            String FolderPath = Path.Combine(Server.MapPath("~/ VehicleImages"), ImageFileName);
            if(System.IO.File.Exists(FolderPath))
            {
                System.IO.File.Delete(FolderPath);
            }
            //resim Silindi
            return RedirectToAction("Index");
        }





        [HttpGet]
        public ActionResult SaveImages()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveImages(String hiddenId, HttpPostedFileBase UploadedImage)
        {
            if(UploadedImage.ContentLength > 0)
            {
               String ImageFileName = hiddenId + "jpg";
                String FolderPath = Path.Combine(Server.MapPath("~/VehicleImages"), ImageFileName);
                UploadedImage.SaveAs(FolderPath);
            }
            ViewBag.Message = hiddenId + ".jpg İsimli Resim Başarıyla Yüklendi";
            return View();
        }   

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/VehicleYonet/Create.cshtml
@model WebApplication1.Models.Tb1_Araclar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Tb1_Araclar</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Marka, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Marka, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Marka, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ModelYili, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModelYili, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModelYili, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Yakit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Yakit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Yakit, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Vites, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vites, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vites, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WebApplication1/WebApplication1/Views/VehicleYonet/Delete.cshtml
        @model WebApplication1.Models.Tb1_Araclar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <link href="~/Css/stilim.css" rel="stylesheet" />
</head>
<body>
    <h3>Bu Aracı Silmek İstiyormusunuz?</h3>
    <div>
        <h4>Tb1_Araclar</h4>
        <hr />
        @{ 
            var dir = "~/VehicleImages/" + Model.AracId + ".jpg";
            <img src="@Url.Content(dir)" width="300"/>
        }


        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Marka)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Marka)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Model)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Model)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ModelYili)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ModelYili)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Yakit)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Yakit)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Vites)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Vites)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Fiyat)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Fiyat)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

WebApplication1/WebApplication1/Views/VehicleYonet/Details.cshtml
@model WebApplication1.Models.Tb1_Araclar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Tb1_Araclar</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Marka)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Marka)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Model)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Model)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ModelYili)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ModelYili)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Yakit)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Yakit)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Vites)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Vites)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Fiyat)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Fiyat)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.AracId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

WebApplication1/WebApplication1/Views/VehicleYonet/Edit.cshtml
@model WebApplication1.Models.Tb1_Araclar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Tb1_Araclar</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AracId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Marka, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Marka, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Marka, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ModelYili, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ModelYili, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ModelYili, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Yakit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Yakit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Yakit, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Vites, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vites, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vites, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WebApplication1/WebApplication1/Views/VehicleYonet/Index.cshtml
@model IEnumerable<WebApplication1.Models.Tb1_Araclar>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Css/stilim.css" rel="stylesheet" />
</head>
<body>
    <h3>Araç Listesi</h3>
    <p>
        @Html.ActionLink("Arac Ekle", "Create")
    </p>
    <table class="table" cellpadding="5" cellspacing="0" border="1">
        <tr>
            <th>
                .
            </th>
            <th>
                MARKA
            </th>
            <th>
                MODEL
            </th>
            <th>
                MODEL YILI
            </th>
            <th>
                YAKIT
            </th>
            <th>
                VİTES
            </th>
            <th>
                FİYAT
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
           <td>
               @{ 
                   var dir = "/vehicleImages/" + item.AracId + ".jpg";
                   <img src="@Url.Content(dir)" width="180" />
               }
           </td>
            
            
            <td>
                @Html.DisplayFor(modelItem => item.Marka)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelYili)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Yakit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vites)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fiyat)
            </td>
            <td>
                @Html.ActionLink("Güncelle", "Edit", new { id = item.AracId }) |
                @Html.ActionLink("Detay", "Details", new { id = item.AracId }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.AracId })
                @Html.ActionLink("Resim Yükle", "SaveImages", new { id = item.AracId })
                
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

WebApplication1/WebApplication1/Views/VehicleYonet/SaveImages.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveImages</title>
</head>
<body>
    <div> 
        <h2>Araç Resim Ekle</h2>
        @using (Html.BeginForm("SaveImages","VehicleYonet",FormMethod.Post, new {enctype="multipart/form-data"}))
            {
            @Html.Hidden("HiddenId",Url.RequestContext.RouteData.Values["id"])
                <p>
                    @Html.TextBox("UploadedImage", "", new {type="File"})
                </p>
                <p>
                    <input type="submit" value="Yükle" >
                </p>
            }
        @{ 
            if (ViewBag.Message != null)
                {
                var dir = "~/VehicleImages/" + Url.RequestContext.RouteData.Values["id"] + ".jpg";
                @ViewBag.Message
                <p>
                    <img src="@Url.Content(dir)" width="300"/>
                </p>
            }
        }



        <p>@Html.ActionLink("Araç Listesi","Index")</p>



    </div>
</body>
</html>